object Dependency {
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Version.kotlin}"
    const val appCompat = "androidx.appcompat:appcompat:${Version.androidX}"
    const val ktx = "androidx.core:core-ktx:${Version.androidX}"
    const val cardView = "androidx.cardview:cardview:${Version.cardView}"
    const val recyclerView = "androidx.recyclerview:recyclerview:${Version.recyclerView}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Version.constraintLayout}"
    const val lifecycle = "androidx.lifecycle:lifecycle-extensions:${Version.lifecycle}"
    const val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.lifecycle}"
    const val liveData = "androidx.lifecycle:lifecycle-livedata:${Version.lifecycle}"
    const val daggerAndroid = "com.google.dagger:dagger-android:${Version.dagger}"
    const val daggerSupport = "com.google.dagger:dagger-android-support:${Version.dagger}"
    const val daggerProcessor = "com.google.dagger:dagger-compiler:${Version.dagger}"
    const val daggerAndroidProcessor = "com.google.dagger:dagger-android-processor:${Version.dagger}"
    const val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Version.threeTenAbp}"
    const val zxing = "com.github.kenglxn.QRGen:android:${Version.zxing}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Version.retrofit}"
    const val moshiConverter = "com.squareup.retrofit2:converter-moshi:${Version.retrofit}"
    const val moshi = "com.squareup.moshi:moshi-kotlin-codegen:${Version.moshi}"
    const val junit = "junit:junit:${Version.junit}"
    const val androidTestRunner = "androidx.test:runner:${Version.androidTestRunner}"
    const val androidJUnit = "androidx.test.ext:junit:${Version.androidJUnit}"
    const val androidTestRules = "androidx.test:rules:${Version.androidTestRules}"
    const val espresso = "androidx.test.espresso:espresso-core:${Version.espresso}"
    const val espressoContrib = "androidx.test.espresso:espresso-contrib:${Version.espresso}"
}

object Version {
    const val kotlin = "1.3.50"
    const val androidX = "1.1.0"
    const val recyclerView = "1.0.0"
    const val cardView = "1.0.0"
    const val constraintLayout = "1.1.3"
    const val lifecycle = "2.1.0"
    const val dagger = "2.24"
    const val moshi = "1.8.0"
    const val zxing = "2.6.0"
    const val threeTenAbp = "1.2.1"
    const val retrofit = "2.6.1"
    const val junit = "4.12"
    const val androidTestRunner = "1.2.0"
    const val androidJUnit= "1.1.1"
    const val androidTestRules= "1.1.0"
    const val espresso = "3.2.0"
}